name: chain-service

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - chain_service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html

networks:
  chain_service:
    driver: bridge