name: chain-service

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - chain_service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html

  backend:
    build: ./backend/main
    container_name: backend_main
    ports:
      - "8000:8000"
    depends_on:
      - webdb
    networks:
      - chain_service
    volumes:
      - ./backend/main:/app
    environment:
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT}
    env_file:
      - .env

  webdb:
    container_name: webdb
    image: postgres:16
    networks:
      - chain_service
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
    env_file:
      - .env

networks:
  chain_service:
    driver: bridge